spring:
  application:
    name: BancoTalentosBackend
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
  profiles:
    active: dev
jwt:
  expiration: ${JWT_EXPIRATION_MILLISECONDS} # 48 hours in milliseconds
  secret: ${JWT_SECRET}

# Configuración de logging
logging:
  level:
    root: info
    org.springframework.web: debug
    com.iotdml.configsrf: debug
  file:
    name: logs/app-logs.log
    path: logs
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"